# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4163473b59de63115faab1c0259e8fad3a423e02b71417ed9e5bd1a083efb3d54f394f9870826830a17b3aa818d2ee0a784b50a48651476a303f5bb0b67ae63b

test:
  secret_key_base: 41c5fd92ca8d9d10ba3a5dabe1eb5602111eb1b6056b04c9f494e1db6a71ee0530b47c5aa33017eebe592fdf50451823c2dfb353b34180f4f540ca44b6975a14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
